#pragma once

#define TRI_LAYER_LOWER_LAYER 1
#define TRI_LAYER_UPPER_LAYER 2
#define TRI_LAYER_ADJUST_LAYER 3

// #define MASTER_LEFT

#define ENCODER_DIRECTION_FLIP
// #define ENCODER_RESOLUTION 4

#define OLED_FONT_H "cocklesgeekfont.c"

#define RGBLIGHT_SLEEP
#define RGBLIGHT_DEFAULT_ON false
#define RGBLIGHT_DEFAULT_HUE 170
#define RGBLIGHT_DEFAULT_SAT 50
#define RGBLIGHT_DEFAULT_VAL 40

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

// Vial Support
// #define VIAL_KEYBOARD_UID { 0x05, 0xCD, 0x9F, 0x8A, 0xF4, 0xDF, 0xDE, 0xB2 }

// The four corners
// #define VIAL_UNLOCK_COMBO_ROWS { 0, 5, 3, 8 }
// #define VIAL_UNLOCK_COMBO_COLS { 0, 0, 0, 0 }