TRI_LAYER_ENABLE = yes

RGBLIGHT_ENABLE = no
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
OLED_ENABLE = yes

MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
WPM_ENABLE = no

COMBO_ENABLE = yes

CONSOLE_ENABLE = no
LTO_ENABLE = yes
# VIA_ENABLE = yes
# VIAL_ENABLE = yes

# QMK_SETTINGS = no
# LAYER_LOCK_ENABLE = no
# REPEAT_KEY_ENABLE = no